config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'hospitals#index'
  resources :hospitals
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  require 'csv'
  require 'open-uri'
  require 'nokogiri'
end

app/controllers/hospitals_controller.rb
# frozen_string_literal: true

class HospitalsController < ApplicationController

  BASE_URL = "https://byoinnavi.jp"

  def index
    respond_to do |format|
      format.html
      format.csv do
        export_csv(params[:target_path])
      end
  rescue StandardError => e
    Rails.logger.error(e)
    end
  end

  private

  def export_csv(target_path)
    hospital_data = read_data(target_path)
    send_data(create_csv(hospital_data), filename: '病院ナビ.csv', type: :csv)
  end

  def read_data(target_path)
    data = []
    loop do
      url = BASE_URL + target_path
      doc = Nokogiri::HTML.parse(open(url))
      doc.css('.corp_table').css('.corp.corp_type_clinic').each do |element|
        name = element.search('.corp_name a').text
        phone_number = element.search('.clinic_tel').text.gsub(/(\r\n|\n|-)/, '')
        address = element.search('.clinic_address').children.first.text.gsub(/(\r\n|\n)/, '')
        hospital_url = element.search('.clinic_url a').attr('href')&.value
        data << { name: name, phone_number: phone_number, address: address, hospital_url: hospital_url }
      end
      target_path = doc.search('.pagination_next').attr('href')&.value
      break unless target_path
    end
    data
  end

  def create_csv(hospital_data)
    bom = "\uFEFF"
    CSV.generate(bom) do |csv|
      column_names = %w[病院名 電話番号 住所 病院のサイトURL]
      csv << column_names
      hospital_data.each do |d|
        csv << [
          d[:name], 
          d[:phone_number],
          d[:address],
          d[:hospital_url]
        ]
      end
    end
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/hospitals_helper.rb
# frozen_string_literal: true

module HospitalsHelper
end

app/views/hospitals/index.html.erb
<style>
p.attention {
 color: red;
}
</style>

<h1>病院ナビスクレイピング</h1>
病院名・電話番号・住所・病院のサイトURLを出力します
全てのページネーションのデータを取得できます
<p>ex) /tokyo/bunkyoku/000</p>

<p class="attention">スクレイピングは対象ページのサーバーに負荷をかけることを留意ください</p>
<%= form_tag(hospitals_path(format: :csv), method: :get, ) do %>
    <p>
    <%= label_tag :url, "url" %><br>
    <%= text_field_tag :target_path %>
    </p>
    <br>
    <p>
    <%= submit_tag "csvで出力する" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OtameshiScraping</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>